In [1]:
import numpy as np



In [2]:
X = np.array(([1 , 2] , [2 , 3] , [3 , 1] , [2 , 5] , [4 , 3]))
Y = np.array((1 , 1 , 1 , 0 , 0))

In [ ]:
X = np.hstack((np.ones((X.shape[0],1)),X))

In [ ]:
def sigmoid(z): 
    return 1 / (1 + np.exp(-z))

In [ ]:
def loss(theta , X , Y):
    L = 0
    for x , y in zip (X , Y):
        if y == 0:
            L += - np.log(1 - sigmoid(np.dot(theta , x)))
        else:
            L += - np.log(sigmoid(np.dot(theta, x)))
    return L

In [ ]:
def gradient(theta , X , Y):
    G = 0
    for x , y in zip(X , Y):
        G += (sigmoid(np.dot(theta ,x )) - y) * x
    return G

In [ ]:
from scipy.optimize import minimize

In [ ]:
initial_theta = np.zeros(X.shape[1])
result = minimize(loss, initial_theta, args= (X , Y), method = 'BFGS' , jac = gradient)
result

  message: Optimization terminated successfully.
  success: True
   status: 0
      fun: 1.3090013249363731e-06
        x: [ 9.493e+01 -1.749e+01 -1.472e+01]
      nit: 26
      jac: [ 1.028e-06  2.066e-06  5.413e-06]
 hess_inv: [[ 1.488e+07 -2.802e+06 -2.233e+06]
            [-2.802e+06  5.276e+05  4.204e+05]
            [-2.233e+06  4.204e+05  3.350e+05]]
     nfev: 28
     njev: 28

In [ ]:
theta =  result.x
theta

array([ 94.92806523, -17.49268406, -14.72125792])

In [ ]:
x_pred = np.array([1 , 1 , 4])

In [ ]:
prob_pred = sigmoid(np.dot(theta , x_pred))
prob_pred

np.float64(0.9999999912161367)

In [ ]:
y_pred = 1 if prob_pred >= 0.5 else 0
y_pred

1

In [ ]:
a = -theta[1]/theta[2]
b = -theta[0]/theta[2]

In [3]:
import matplotlib.pyplot as plt


In [4]:
plt.scatter(X[Y == 1][: , 1] , X[Y == 1][: , 2], color = 'blue')
plt.scatter(X[Y == 0][: , 1] , X[Y == 0][: , 2], color = 'red')
plt.scatter(x_pred[1] , x_pred[2], color = 'green' , marker ='x', s=100 )


X1 = np.linspace(0 , 5 , 100)
X2 = a*X1 + b
plt.plot(X1 , X2 , color = 'yellow')

IndexError: index 2 is out of bounds for axis 1 with size 2