In [1]:
import openpyxl
import numpy as np


In [2]:
workbook = openpyxl.load_workbook("68IT1.xlsx")

In [3]:
sheet = workbook.active

In [4]:
start_row = 11
end_row = 65
column1 = 'G'
column2 = 'H'


In [5]:
X1 = np.array([])
Y1 = np.array([])

In [40]:
for row in range(start_row , end_row + 1):
    X = sheet[f'{column1}{row}'].value
    X1 = np.append(X1 , X)
len(X1)


55

In [41]:
for row in range(start_row , end_row + 1):
    Y = sheet[f'{column2}{row}'].value
    Y1 = np.append(Y1 , Y)
len(Y1)

55

In [42]:
X2 = np.expand_dims(X1 , axis = 1)
X2

array([[4.5],
       [6.0],
       [7.5],
       [4.0],
       [6.5],
       [7.5],
       [8.5],
       [6.0],
       [5.0],
       [8.0],
       [2.0],
       [5.0],
       [6.0],
       [9.0],
       [5.5],
       [8.5],
       [4.0],
       [None],
       [4.5],
       [6],
       [7],
       [8],
       [0.5],
       [3],
       [5],
       [7],
       [6],
       [4],
       [5],
       [4.5],
       [5.5],
       [4],
       [7],
       [None],
       [4],
       [2.5],
       [9.5],
       [8],
       [4],
       [6],
       [7.5],
       [None],
       [10],
       [3],
       [6.5],
       [6],
       [8.5],
       [2.5],
       [7],
       [6.5],
       [5],
       [3],
       [5],
       [7],
       [4.5]], dtype=object)

In [44]:
Y2 = np.expand_dims(Y1 , axis = 1)
Y2

array([[9.5],
       [6.0],
       [9.0],
       [10.0],
       [5.0],
       [0.0],
       [7.5],
       [8.0],
       [8.5],
       [8.0],
       [4.0],
       [7.0],
       [8.0],
       [8.0],
       [10.0],
       [10.0],
       [4.5],
       [None],
       [6.5],
       [7.5],
       [8],
       [3],
       [3],
       [5.5],
       [8],
       [9.5],
       [6],
       [9],
       [4.5],
       [5],
       [7],
       [2],
       [7],
       [4.5],
       [None],
       [7],
       [9.5],
       [7.5],
       [4.5],
       [8],
       [5],
       [None],
       [4],
       [7],
       [10],
       [3.5],
       [8.5],
       [2.5],
       [10],
       [9],
       [8],
       [7.5],
       [7],
       [10],
       [7.5]], dtype=object)

In [46]:
Z = np.concatenate((X2 , Y2), axis = 1)
Z

array([[4.5, 9.5],
       [6.0, 6.0],
       [7.5, 9.0],
       [4.0, 10.0],
       [6.5, 5.0],
       [7.5, 0.0],
       [8.5, 7.5],
       [6.0, 8.0],
       [5.0, 8.5],
       [8.0, 8.0],
       [2.0, 4.0],
       [5.0, 7.0],
       [6.0, 8.0],
       [9.0, 8.0],
       [5.5, 10.0],
       [8.5, 10.0],
       [4.0, 4.5],
       [None, None],
       [4.5, 6.5],
       [6, 7.5],
       [7, 8],
       [8, 3],
       [0.5, 3],
       [3, 5.5],
       [5, 8],
       [7, 9.5],
       [6, 6],
       [4, 9],
       [5, 4.5],
       [4.5, 5],
       [5.5, 7],
       [4, 2],
       [7, 7],
       [None, 4.5],
       [4, None],
       [2.5, 7],
       [9.5, 9.5],
       [8, 7.5],
       [4, 4.5],
       [6, 8],
       [7.5, 5],
       [None, None],
       [10, 4],
       [3, 7],
       [6.5, 10],
       [6, 3.5],
       [8.5, 8.5],
       [2.5, 2.5],
       [7, 10],
       [6.5, 9],
       [5, 8],
       [3, 7.5],
       [5, 7],
       [7, 10],
       [4.5, 7.5]], dtype=object)