In [33]:
import numpy as np
X = np.array([0 , 1 , 2 , 3 , 4 , 5 , 6 , 7 , 8 , 9 , 10 , 11 , 12 , 13 , 14])
Y = np.array([7 , 9 , 2 , 4 , -1 , 0 , -4 , -2 , -5 , -3 , -3 , 0 , 2 , 1 , 8])

In [34]:
n = len(X)
n

15

In [35]:
n_train = 12
n_test = 3

In [36]:
index_train = np.random.choice(range(n),n_train,replace=False)
index_train

array([ 6, 14,  3, 11,  1, 13,  5,  9,  2,  8, 10,  7])

In [37]:
X_train = [int(X[i]) for i in index_train]
X_train

[6, 14, 3, 11, 1, 13, 5, 9, 2, 8, 10, 7]

In [38]:
Y_train = [int(Y[i]) for i in index_train]
Y_train

[-4, 8, 4, 0, 9, 1, 0, -3, 2, -5, -3, -2]

In [39]:
index_test = [i for i in range(n) if i not in index_train]
index_test

[0, 4, 12]

In [40]:
X_test = [int(X[i]) for i in index_test]
X_test

[0, 4, 12]

In [41]:
Y_test = [int(Y[i]) for i in index_test]
Y_test

[7, -1, 2]

In [42]:
X_expand = np.expand_dims(X_train,axis = 1)
X_expand

array([[ 6],
       [14],
       [ 3],
       [11],
       [ 1],
       [13],
       [ 5],
       [ 9],
       [ 2],
       [ 8],
       [10],
       [ 7]])

In [43]:
Y_expand = np.expand_dims(Y_train, axis = 1)
Y_expand

array([[-4],
       [ 8],
       [ 4],
       [ 0],
       [ 9],
       [ 1],
       [ 0],
       [-3],
       [ 2],
       [-5],
       [-3],
       [-2]])

In [44]:
V = np.concatenate((X_expand**0,X_expand,X_expand**2),axis = 1)
V

array([[  1,   6,  36],
       [  1,  14, 196],
       [  1,   3,   9],
       [  1,  11, 121],
       [  1,   1,   1],
       [  1,  13, 169],
       [  1,   5,  25],
       [  1,   9,  81],
       [  1,   2,   4],
       [  1,   8,  64],
       [  1,  10, 100],
       [  1,   7,  49]])

In [46]:
theta = np.linalg.inv(V.T.dot(V)).dot(V.T).dot(Y_train)
theta

array([11.88939493, -3.97706912,  0.25530575])

In [47]:
X_test_expand = np.expand_dims(X_test,axis = 1)
X_test_expand

array([[ 0],
       [ 4],
       [12]])

In [48]:
Y_test_expand = np.expand_dims(Y_test, axis = 1)
Y_test_expand

array([[ 7],
       [-1],
       [ 2]])

In [50]:
V_test = np.concatenate((X_test_expand**0,X_test_expand,X_test_expand**2), axis = 1)
V_test

array([[  1,   0,   0],
       [  1,   4,  16],
       [  1,  12, 144]])

In [52]:
MSE = 1/3 * np.linalg.norm(Y_test_expand - (V_test * theta))**2
float(MSE)

1438.350633787199

In [55]:
B = theta.dot([1,11.5,11.5**2])
float(B)

-0.08271510308100005