In [1]:
import numpy as np 
import openpyxl


In [2]:
workbook = openpyxl.load_workbook("68IT1.xlsx")

In [3]:
sheet = workbook.active

In [26]:
column1 = 'G'
column2 = 'H'
column3 = 'I'

In [5]:
start_row = 11
end_row = 65

In [27]:
X1 = np.array([])
Y1 = np.array([])
Z1 = np.array([])

In [7]:
for row in range(start_row , end_row + 1):
    X = sheet[f'{column1}{row}'].value
    X1 = np.append(X1 , X)
X1

array([4.5, 6.0, 7.5, 4.0, 6.5, 7.5, 8.5, 6.0, 5.0, 8.0, 2.0, 5.0, 6.0,
       9.0, 5.5, 8.5, 4.0, None, 4.5, 6, 7, 8, 0.5, 3, 5, 7, 6, 4, 5, 4.5,
       5.5, 4, 7, None, 4, 2.5, 9.5, 8, 4, 6, 7.5, None, 10, 3, 6.5, 6,
       8.5, 2.5, 7, 6.5, 5, 3, 5, 7, 4.5], dtype=object)

In [8]:
for row in range(start_row , end_row + 1):
    Y = sheet[f'{column2}{row}'].value
    Y1 = np.append(Y1 , Y)
Y1

array([9.5, 6.0, 9.0, 10.0, 5.0, 0.0, 7.5, 8.0, 8.5, 8.0, 4.0, 7.0, 8.0,
       8.0, 10.0, 10.0, 4.5, None, 6.5, 7.5, 8, 3, 3, 5.5, 8, 9.5, 6, 9,
       4.5, 5, 7, 2, 7, 4.5, None, 7, 9.5, 7.5, 4.5, 8, 5, None, 4, 7, 10,
       3.5, 8.5, 2.5, 10, 9, 8, 7.5, 7, 10, 7.5], dtype=object)

In [28]:
for row in range(start_row , end_row + 1):
    Z = sheet[f'{column3}{row}'].value
    Z1 = np.append(Z1 , Z)
Z1

array([2.5, 2.0, 4.5, 3.0, 0.5, None, 8, 4, 1.5, 3.5, 3.5, 7, 7, 4.5, 6.5,
       9.5, 7, None, 2.5, 2.5, 8, 7.5, 3.5, 0, 2.5, 6, 2, 1.5, 4.5, 1,
       2.5, 0.5, 0.5, None, 0.5, 1, 8.5, 8.5, 0, 6.5, 4, 0, 5.5, 1.5, 7,
       6.5, 7.5, 2, 5, 7, 7.5, 1, 5, 6.5, 5], dtype=object)

In [9]:
Y_expand = np.expand_dims(Y1 , axis = 1)
Y_expand

array([[9.5],
       [6.0],
       [9.0],
       [10.0],
       [5.0],
       [0.0],
       [7.5],
       [8.0],
       [8.5],
       [8.0],
       [4.0],
       [7.0],
       [8.0],
       [8.0],
       [10.0],
       [10.0],
       [4.5],
       [None],
       [6.5],
       [7.5],
       [8],
       [3],
       [3],
       [5.5],
       [8],
       [9.5],
       [6],
       [9],
       [4.5],
       [5],
       [7],
       [2],
       [7],
       [4.5],
       [None],
       [7],
       [9.5],
       [7.5],
       [4.5],
       [8],
       [5],
       [None],
       [4],
       [7],
       [10],
       [3.5],
       [8.5],
       [2.5],
       [10],
       [9],
       [8],
       [7.5],
       [7],
       [10],
       [7.5]], dtype=object)

In [10]:
X_expand = np.expand_dims(X1 , axis = 1)
X_expand

array([[4.5],
       [6.0],
       [7.5],
       [4.0],
       [6.5],
       [7.5],
       [8.5],
       [6.0],
       [5.0],
       [8.0],
       [2.0],
       [5.0],
       [6.0],
       [9.0],
       [5.5],
       [8.5],
       [4.0],
       [None],
       [4.5],
       [6],
       [7],
       [8],
       [0.5],
       [3],
       [5],
       [7],
       [6],
       [4],
       [5],
       [4.5],
       [5.5],
       [4],
       [7],
       [None],
       [4],
       [2.5],
       [9.5],
       [8],
       [4],
       [6],
       [7.5],
       [None],
       [10],
       [3],
       [6.5],
       [6],
       [8.5],
       [2.5],
       [7],
       [6.5],
       [5],
       [3],
       [5],
       [7],
       [4.5]], dtype=object)

In [11]:
Z = np.concatenate((X_expand , Y_expand) , axis = 1)
Z

array([[4.5, 9.5],
       [6.0, 6.0],
       [7.5, 9.0],
       [4.0, 10.0],
       [6.5, 5.0],
       [7.5, 0.0],
       [8.5, 7.5],
       [6.0, 8.0],
       [5.0, 8.5],
       [8.0, 8.0],
       [2.0, 4.0],
       [5.0, 7.0],
       [6.0, 8.0],
       [9.0, 8.0],
       [5.5, 10.0],
       [8.5, 10.0],
       [4.0, 4.5],
       [None, None],
       [4.5, 6.5],
       [6, 7.5],
       [7, 8],
       [8, 3],
       [0.5, 3],
       [3, 5.5],
       [5, 8],
       [7, 9.5],
       [6, 6],
       [4, 9],
       [5, 4.5],
       [4.5, 5],
       [5.5, 7],
       [4, 2],
       [7, 7],
       [None, 4.5],
       [4, None],
       [2.5, 7],
       [9.5, 9.5],
       [8, 7.5],
       [4, 4.5],
       [6, 8],
       [7.5, 5],
       [None, None],
       [10, 4],
       [3, 7],
       [6.5, 10],
       [6, 3.5],
       [8.5, 8.5],
       [2.5, 2.5],
       [7, 10],
       [6.5, 9],
       [5, 8],
       [3, 7.5],
       [5, 7],
       [7, 10],
       [4.5, 7.5]], dtype=object)

In [12]:
Z1 = np.array([row for row in Z if None not in row])
Z1

array([[4.5, 9.5],
       [6.0, 6.0],
       [7.5, 9.0],
       [4.0, 10.0],
       [6.5, 5.0],
       [7.5, 0.0],
       [8.5, 7.5],
       [6.0, 8.0],
       [5.0, 8.5],
       [8.0, 8.0],
       [2.0, 4.0],
       [5.0, 7.0],
       [6.0, 8.0],
       [9.0, 8.0],
       [5.5, 10.0],
       [8.5, 10.0],
       [4.0, 4.5],
       [4.5, 6.5],
       [6, 7.5],
       [7, 8],
       [8, 3],
       [0.5, 3],
       [3, 5.5],
       [5, 8],
       [7, 9.5],
       [6, 6],
       [4, 9],
       [5, 4.5],
       [4.5, 5],
       [5.5, 7],
       [4, 2],
       [7, 7],
       [2.5, 7],
       [9.5, 9.5],
       [8, 7.5],
       [4, 4.5],
       [6, 8],
       [7.5, 5],
       [10, 4],
       [3, 7],
       [6.5, 10],
       [6, 3.5],
       [8.5, 8.5],
       [2.5, 2.5],
       [7, 10],
       [6.5, 9],
       [5, 8],
       [3, 7.5],
       [5, 7],
       [7, 10],
       [4.5, 7.5]], dtype=object)

In [13]:
X = np.array([row[0] for row in Z1])  # Lấy cột 1
Y = np.array([row[1] for row in Z1])  # Lấy cột 2

In [14]:
X = X.reshape(-1,1)
X

array([[ 4.5],
       [ 6. ],
       [ 7.5],
       [ 4. ],
       [ 6.5],
       [ 7.5],
       [ 8.5],
       [ 6. ],
       [ 5. ],
       [ 8. ],
       [ 2. ],
       [ 5. ],
       [ 6. ],
       [ 9. ],
       [ 5.5],
       [ 8.5],
       [ 4. ],
       [ 4.5],
       [ 6. ],
       [ 7. ],
       [ 8. ],
       [ 0.5],
       [ 3. ],
       [ 5. ],
       [ 7. ],
       [ 6. ],
       [ 4. ],
       [ 5. ],
       [ 4.5],
       [ 5.5],
       [ 4. ],
       [ 7. ],
       [ 2.5],
       [ 9.5],
       [ 8. ],
       [ 4. ],
       [ 6. ],
       [ 7.5],
       [10. ],
       [ 3. ],
       [ 6.5],
       [ 6. ],
       [ 8.5],
       [ 2.5],
       [ 7. ],
       [ 6.5],
       [ 5. ],
       [ 3. ],
       [ 5. ],
       [ 7. ],
       [ 4.5]])

In [15]:
Y = Y.reshape(-1,1)
Y

array([[ 9.5],
       [ 6. ],
       [ 9. ],
       [10. ],
       [ 5. ],
       [ 0. ],
       [ 7.5],
       [ 8. ],
       [ 8.5],
       [ 8. ],
       [ 4. ],
       [ 7. ],
       [ 8. ],
       [ 8. ],
       [10. ],
       [10. ],
       [ 4.5],
       [ 6.5],
       [ 7.5],
       [ 8. ],
       [ 3. ],
       [ 3. ],
       [ 5.5],
       [ 8. ],
       [ 9.5],
       [ 6. ],
       [ 9. ],
       [ 4.5],
       [ 5. ],
       [ 7. ],
       [ 2. ],
       [ 7. ],
       [ 7. ],
       [ 9.5],
       [ 7.5],
       [ 4.5],
       [ 8. ],
       [ 5. ],
       [ 4. ],
       [ 7. ],
       [10. ],
       [ 3.5],
       [ 8.5],
       [ 2.5],
       [10. ],
       [ 9. ],
       [ 8. ],
       [ 7.5],
       [ 7. ],
       [10. ],
       [ 7.5]])

In [16]:
n =len(X)

In [17]:
n_train = 40
n_test = 11

In [18]:
index_train = np.random.choice(range(n) ,n_train,replace=True )
index_train

array([26, 39, 12, 44, 46, 30, 38, 29, 21, 46, 25,  3, 49, 17, 31, 50,  2,
       31, 14, 14, 37, 15, 24, 41, 46, 21, 38,  5, 27, 29, 19, 17, 14, 38,
       11, 34, 21, 37,  2, 43])

In [19]:
X_train = np.array([float(X[i]) for i in index_train])
X_train

C:\Users\DELL\AppData\Local\Temp\ipykernel_13388\2489936020.py:1: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  X_train = np.array([float(X[i]) for i in index_train])


array([ 4. ,  3. ,  6. ,  7. ,  5. ,  4. , 10. ,  5.5,  0.5,  5. ,  6. ,
        4. ,  7. ,  4.5,  7. ,  4.5,  7.5,  7. ,  5.5,  5.5,  7.5,  8.5,
        7. ,  6. ,  5. ,  0.5, 10. ,  7.5,  5. ,  5.5,  7. ,  4.5,  5.5,
       10. ,  5. ,  8. ,  0.5,  7.5,  7.5,  2.5])

In [20]:
Y_train = np.array([float(Y[i]) for i in index_train])
Y_train

C:\Users\DELL\AppData\Local\Temp\ipykernel_13388\373666442.py:1: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  Y_train = np.array([float(Y[i]) for i in index_train])


array([ 9. ,  7. ,  8. , 10. ,  8. ,  2. ,  4. ,  7. ,  3. ,  8. ,  6. ,
       10. , 10. ,  6.5,  7. ,  7.5,  9. ,  7. , 10. , 10. ,  5. , 10. ,
        9.5,  3.5,  8. ,  3. ,  4. ,  0. ,  4.5,  7. ,  8. ,  6.5, 10. ,
        4. ,  7. ,  7.5,  3. ,  5. ,  9. ,  2.5])

In [21]:
index_test = [i for i in range(n) if i not in index_train]
index_test

[0,
 1,
 4,
 6,
 7,
 8,
 9,
 10,
 13,
 16,
 18,
 20,
 22,
 23,
 28,
 32,
 33,
 35,
 36,
 40,
 42,
 45,
 47,
 48]

In [22]:
X_test = np.array([float(X[i]) for i in index_test])
X_test

C:\Users\DELL\AppData\Local\Temp\ipykernel_13388\2908310555.py:1: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  X_test = np.array([float(X[i]) for i in index_test])


array([4.5, 6. , 6.5, 8.5, 6. , 5. , 8. , 2. , 9. , 4. , 6. , 8. , 3. ,
       5. , 4.5, 2.5, 9.5, 4. , 6. , 6.5, 8.5, 6.5, 3. , 5. ])

In [23]:
Y_test = np.array([float(X[i]) for i in index_test])
Y_test

C:\Users\DELL\AppData\Local\Temp\ipykernel_13388\3796745084.py:1: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  Y_test = np.array([float(X[i]) for i in index_test])


array([4.5, 6. , 6.5, 8.5, 6. , 5. , 8. , 2. , 9. , 4. , 6. , 8. , 3. ,
       5. , 4.5, 2.5, 9.5, 4. , 6. , 6.5, 8.5, 6.5, 3. , 5. ])

In [24]:
X_expand = np.expand_dims(X_train , axis = 1)
X_expand

array([[ 4. ],
       [ 3. ],
       [ 6. ],
       [ 7. ],
       [ 5. ],
       [ 4. ],
       [10. ],
       [ 5.5],
       [ 0.5],
       [ 5. ],
       [ 6. ],
       [ 4. ],
       [ 7. ],
       [ 4.5],
       [ 7. ],
       [ 4.5],
       [ 7.5],
       [ 7. ],
       [ 5.5],
       [ 5.5],
       [ 7.5],
       [ 8.5],
       [ 7. ],
       [ 6. ],
       [ 5. ],
       [ 0.5],
       [10. ],
       [ 7.5],
       [ 5. ],
       [ 5.5],
       [ 7. ],
       [ 4.5],
       [ 5.5],
       [10. ],
       [ 5. ],
       [ 8. ],
       [ 0.5],
       [ 7.5],
       [ 7.5],
       [ 2.5]])

In [25]:
Y_expand = np.expand_dims(Y_train , axis = 1)
Y_expand

array([[ 9. ],
       [ 7. ],
       [ 8. ],
       [10. ],
       [ 8. ],
       [ 2. ],
       [ 4. ],
       [ 7. ],
       [ 3. ],
       [ 8. ],
       [ 6. ],
       [10. ],
       [10. ],
       [ 6.5],
       [ 7. ],
       [ 7.5],
       [ 9. ],
       [ 7. ],
       [10. ],
       [10. ],
       [ 5. ],
       [10. ],
       [ 9.5],
       [ 3.5],
       [ 8. ],
       [ 3. ],
       [ 4. ],
       [ 0. ],
       [ 4.5],
       [ 7. ],
       [ 8. ],
       [ 6.5],
       [10. ],
       [ 4. ],
       [ 7. ],
       [ 7.5],
       [ 3. ],
       [ 5. ],
       [ 9. ],
       [ 2.5]])